spring.application.name=SpringEcom

spring.datasource.url=jdbc:postgresql://localhost:5432/STARK
spring.datasource.username=postgres
spring.datasource.password=11223344
spring.jpa.hibernate.ddl-auto=update